#!/bin/bash

CURRENTDIR="`pwd`"

HEIGHT=30
WIDTH=40
CHOICE_HEIGHT=25
BACKTITLE="POS Application Service"
TITLE="Development"
MENU="Selection: "

echo "" >/tmp/MENU2_dia.out
WIDGET=(--and-widget --keep-window --begin 46 2 --cr-wrap --tailbox /tmp/MENU2_dia.out 30 170)

OPTIONS=( 1 "Running Contianers" 
          2 "Start Container" 
          3 "Stop Container" 
          4 "Attach to a Container" 
	  5 "List Network Interfaces" 
	  6 "Wipe Everything" 
	  7 "Create RTI Image" 
	  8 "List Images" 
	  9 "Wipe Images" 

	  a "Setup AWS" 
	  i "Install Dependancies" )

CHOICE=$(dialog --begin 2 2 \
		--keep-window \
		--backtitle "$BACKTITLE -> Dev / Build" \
		--title "$TITLE" \
		--menu "$MENU" \
		$HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		$WIDGET \
		2>&1 >/dev/tty) 

case $CHOICE in
	1)
		$CURRENTDIR/bin/container_status 2>&1 >/tmp/MENU2_dia.out &
#		dialog --keep-window --begin 2 50 --cr-wrap --trim --title "List Running Containers" --backtitle "$BACKTITLE -> Dev / Build" --tailbox /tmp/MENU2_dia.out 30 170 >/dev/tty
		;;
	2)
		$CURRENTDIR/bin/launch_container
		;;
	3)
		$CURRENTDIR/bin/stop_container
		;;
	4)
		$CURRENTDIR/bin/attach_container
		;;
	5)
		$CURRENTDIR/bin/list_nics 2>&1 >/tmp/MENU2_dia.out
		dialog --keep-window --begin 2 50 --cr-wrap --trim --title "List Network Interfaces" --backtitle "$BACKTITLE -> Dev / Build" --tailbox /tmp/MENU2_dia.out 30 180 
		;;
	6)
		$CURRENTDIR/bin/prune-docker
		;;
	7)
		cd $CURRENTDIR/bin
	 	./create-base-image 2>&1 >/tmp/MENU2_dia.out &
		cd $CURRENTDIR
		dialog --keep-window --begin 2 50 --title "Create Installation Media" --backtitle "$BACKTITLE -> Dev / Build" --tailbox /tmp/MENU2_dia.out 30 180
		;;
	8)
		cd $CURRENTDIR/bin
                ./list_image 2>&1 >/tmp/MENU2_dia.out & 
		cd $CURRENTDIR
		dialog --keep-window --begin 2 50 --cr-wrap --trim --title "List Images" --backtitle "$BACKTITLE -> Dev / Build" --tailbox /tmp/MENU2_dia.out 30 180
		;;
	9)
		$CURRENTDIR/bin/wipe_images
		;;
	i)
		$CURRENTDIR/bin/install
		;;
	a)
		$CURRENTDIR/bin/setup_aws
		;;
	*)
		;;
esac
