#!/bin/bash

DOCROOT="`pwd`"
export DOCROOT

HEIGHT=28
WIDTH=35
CHOICE_HEIGHT=25
BACKTITLE="POS Application Service"
TITLE="Development"
MENU="Selection: "

OPTIONS=( 1 "Running Contianers" 
          2 "Start Container" 
          3 "Stop Container" 
          4 "Attach to a Container" 
	  5 "List Network Interfaces" 
	  6 "Wipe Everything" 
	  7 "Create RTI Image" 
	  8 "List Images" 
	  9 "Wipe Images" 
	  a "Setup AWS" 
	  i "Install Dependancies" )

CHOICE=$(dialog --clear \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--menu "$MENU" \
		$HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty) 

case $CHOICE in
	1)
		$DOCROOT/bin/container_status
		;;
	2)
		$DOCROOT/bin/launch_container
		;;
	3)
		$DOCROOT/bin/stop_container
		;;
	4)
		$DOCROOT/bin/attach_container
		;;
	5)
		$DOCROOT/bin/list_nics
		;;
	6)
		$DOCROOT/bin/prune-docker
		;;
	7)
		time $DOCROOT/bin/create-base-image 2>&1
		;;
	8)
		$DOCROOT/bin/list_image | tee /tmp/tailbox.out
		;;
	9)
		$DOCROOT/bin/wipe_images
		;;
	i)
		$DOCROOT/bin/install
		;;
	a)
		$DOCROOT/bin/setup_aws
		;;
esac
