#!/bin/bash

trap '' 2
while :
do
#clear
echo "********************************"
echo "****** POS Backup Menu *********"
echo "****** Free Space: `df -h / | tail -1 | awk '{print $3}'`  *******"
echo "********************************"
echo "* [l] List Cloud Accounts      *"
echo "* [c] Create Cloud Account     *"
echo "* [k] Change Cloud Account Key *"
echo "* [v] View Cloud Account Key   *"
echo "* [g] Get Cloud Account Key    *"
echo "* [d] Delete Cloud Account     *"
echo "* [s] Is Subscriber?           *"
echo "* [a] About                    *"
echo "* [x] Exit the system          *"
echo "********************************"
echo "Enter selection [l,a,k,v,g,d,s,a,x]: "
read selection
case $selection in
l) ./bin/list_cloud_account ; echo "Press enter to continue.." ; read ;;
c) ./bin/create_cloud_account ; echo "Press enter to continue.." ; read ;;
k) ./bin/change_account_key ; echo "Press enter to continue.." ; read  ;;
v) ./bin/view_cloud_key ; echo "Press enter to continue.." ; read  ;;
g) ./bin/get_cloud_key ; echo "Press enter to continue.." ; read  ;;
d) ./bin/delete_cloud_account ; echo "Press enter to continue.." ; read  ;;
s) ./bin/is_subscriber ; echo "Press enter to continue.." ; read  ;;
a) cat ./README.md ; echo "Press enter to continue.." ; read ;;
x)  cd .. ; exit ;;
*) ;;
esac
done
