#!/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

trap '' 2
while :; do
	clear
echo -en "$(date +%T)\n"
printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
printf '\u2503''\033[1m Cloud Backup Menu\033[0m''\n'
printf '\u2523''\u2501''\n'
printf '\u2503'" Free Space: $(df -h /backups | tail -1 | awk '{print $4}')"'\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" 1.\033[0m List Accounts"'\n'
printf '\u2503''\033[1m'" 2.\033[0m Create Account"'\n'
printf '\u2503''\033[1m'" 3.\033[0m Change Key"'\n'
printf '\u2503''\033[1m'" 4.\033[0m View Key"'\n'
printf '\u2503''\033[1m'" 5.\033[0m Get Key"'\n'
printf '\u2503''\033[1m'" 6.\033[0m Delete Account"'\n'
printf '\u2503''\033[1m'" 7.\033[0m Is Subscriber?"'\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" i.\033[0m Info"'\n'
printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
printf '\u2517''\u2501''\n'
	echo -n "Enter selection: "
	read selection
	case $selection in
	1)
		$ROOTDIR/bin/list_cloud_account
		echo "Press enter to continue.."
		read
		;;
	2)
		$ROOTDIR/bin/create_cloud_account
		echo "Press enter to continue.."
		read
		;;
	3)
		$ROOTDIR/bin/change_account_key
		echo "Press enter to continue.."
		read
		;;
	4)
		$ROOTDIR/bin/view_cloud_key
		echo "Press enter to continue.."
		read
		;;
	5)
		$ROOTDIR/bin/get_cloud_key
		echo "Press enter to continue.."
		read
		;;
	6)
		$ROOTDIR/bin/delete_cloud_account
		echo "Press enter to continue.."
		read
		;;
	7)
		$ROOTDIR/bin/is_subscriber
		echo "Press enter to continue.."
		read
		;;
	i)
		cat ./README.md
		echo "Press enter to continue.."
		read
		;;
	x)
		cd ..
		exit
		;;
	*) ;;
	esac
done
