#!/usr/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

#figure out why I have to do the next command manually
#scl enable python27 /usr/bin/bash

trap '' 2
while :; do
	clear

    LGGRN='\033[1;32m'
#    BLUE='\033[1;34m'
    BLUE=''
    GREY='\033[0;37m'
#    CYAN='\033[1;36m'
    CYAN=''
    NC='\033[0m'
    clear
    echo -e "${GREY} $(date +'%x %l:%M %p')${NC}"
    printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
    printf '\u2503'${BLUE}' @ '${NC}'Repo Menu'${NC}'\n'
    printf '\u2503'${LGGRN}' )~'${NC}'\n'
    printf '\u2523''\u2501''\n'
echo -e "\u2503 Status: ${NC}`systemctl status httpd 2>/dev/null | grep Active | cut -d" " -f5`"
printf '\u2503''\n'
printf '\u2503''\033[1m'" 1.\033[0m Start Repo"'\n'
printf '\u2503''\033[1m'" 2.\033[0m Stop Repo"'\n'
printf '\u2503''\033[1m'" 3.\033[0m Create/Update Repo"'\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" i.\033[0m I/C/U Deps"'\n'
printf '\u2503''\033[1m'" r.\033[0m Readme"'\n'
printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
printf '\u2517''\u2501''\n'
	echo -ne "${CYAN}Enter selection:${NC} "
	read selection
	case $selection in
	i)
		cd $ROOTDIR/bin
		time ./install_deps
		echo "Press enter to continue.."
		read
		cd -
		;;
	1)
		cd $ROOTDIR/bin
		./start_repo
		echo "Press enter to continue.."
		read
		cd -
		;;
	2)
		cd $ROOTDIR/bin
		./stop_repo
		echo "Press enter to continue.."
		read
		cd -
		;;
	3)
		cd $ROOTDIR/bin
		time ./update_centos_mirrors
		echo "Press enter to continue.."
		read
		cd -
		;;
	4)
		cd $ROOTDIR/bin
		./promote_prod_repo
		echo "Press enter to continue.."
		read
		cd -
		;;
	r)
		cat README.md | more
		echo "Press enter to continue.."
		read
		cd -
		;;
	x) exit ;;
	*) ;;
	esac
done
