#!/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

trap '' 2
while :; do
	clear
	echo "********************************"
	echo "** MS Linux Support Menu       *"
	echo "********************************"
	echo "* [1] POS Cloud Backup Service *"
	echo "* [2] POS Cloud App Service    *"
	echo "* [3] POS CentOS Repo          *"
	echo "* [4] Misc                     *"
	echo "*                              *"
	echo "* [a] About                    *"
	echo "* [x] Exit                     *"
	echo "********************************"
	echo -n "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/msposbackup
		./MENU
		cd -
		;;
	2)
		cd $ROOTDIR/msposapp
		./MENU
		cd -
		;;
	3)
		cd $ROOTDIR/tfmscentos
		./MENU
		cd -
		;;
	4)
		cd $ROOTDIR/linuxadmin
		./MENU
		cd -
		;;
	a)
		cat ./README.md
		echo "Press enter to continue.."
		read
		;;
	x) exit ;;
	*) ;;
	esac
done
