#!/bin/bash

#trap '' 2
while :
do
clear
echo "********************************"
echo "** Managed Services AWS Menu ***"
echo "********************************"
echo "* [i] POS EC2 Instance service *"
echo "* [b] POS Backup service       *"
echo "* [c] POS Container service    *"
echo "* [s] Status                   *"
echo "* [a] About                    *"
echo "* [d] install Dependancies     *"
echo "* [x] eXit                     *"
echo "********************************"
selection=""
echo -n "Enter selection [i,b,c,s,a,d,x]: "
read selection
case $selection in
i) cd msposinstance ; ./MENU ; echo "Press enter to continue.." ; read ;;
b) cd msposbackup ; ./MENU ; echo "Press enter to continue.." ; read ;;
c) cd msposcontainer ; ./MENU ; echo "Press enter to continue.." ; read ;;
a) cat ./README.md ; echo "Press enter to continue.." ; read ;;
d) ./bin/install ; echo "Press enter to continue.." ; read  ;;
x) exit ;;
*) ;;
esac
done
