#!/usr/bin/bash

HEIGHT=18
WIDTH=35
CHOICE_HEIGHT=15
BACKTITLE="Cloud Services Menu"
TITLE="Managed Services"
MENU="Enter selection: "

OPTIONS=(1 "Cloud Backup Service"
         2 "RTI Cloud Service"
         3 "MS CentOS Repository"
	 4 "Linux Admin Tasks")

CHOICE=$(dialog --clear \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--menu "$MENU" \
		$HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty)

case $CHOICE in
	1)
		./msposbackup/MENU2
		;;
	2)
		./msposapp/MENU2
		;;
	3)
		./tfmscentos/MENU2
		;;
	4)
		./linuxadmin/MENU2
		;;
	*) ;;
esac
exit 0
