#!/bin/bash

export TERM=xterm
trap '' 2
while :
do
#clear
echo "********************************"
echo "** Managed Services Cloud Menu *"
echo "********************************"
echo "* [b] POS Backup service       *"
echo "* [a] POS Application service  *"
echo "* [s] Status                   *"
echo "* [i] Information              *"
echo "* [d] Install/Configure Deps.  *"
echo "* [x] Exit                     *"
echo "********************************"
echo "Enter selection [b,a,s,i,d,x]: "
read selection
case $selection in
b) cd msposbackup ; ./MENU ; cd .. ;;
a) cd msposapp ; ./MENU ; cd .. ;;
s) echo "status here" ; echo "Press enter to continue.." ; read ;;
i) cat ./README.md ; echo "Press enter to continue.." ; read ;;
d) ./bin/install ; echo "Press enter to continue.." ; read  ;;
x) exit ;;
*) ;;
esac
done
