#!/usr/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

#figure out why I have to do the next command manually
#scl enable python27 /usr/bin/bash

trap '' 2
while :; do
	clear
	echo "**************************************"
	echo "** TELEFLORA HOSTED ******************"
	echo "**************************************"
	echo "*                                    *"
	echo "** Staging **			   *"
	echo "* [1] Stage a server		   *"
	echo "* [2] Restore florist data	   *"
	echo "* [3] Upload florist image to EC2	   *"
	echo "*					   *"
	echo "** AWS **                            *"
	echo "* [111] List VPNs                    *"
	echo "* [112] Create VPN Access            *"
	echo "* [113] Remove VPN Access            *"
	echo "* [114] List Instances               *"
	echo "* [115] Start an Instance            *"
	echo "* [116] Stop an Instance             *"
	echo "*                                    *"
	echo "* [i]  Install/Upgrade Deps.         *"
	echo "* [a]  Install/Configure AWS         *"
	echo "* [x]  Exit                          *"
	echo "**************************************"
	echo -n "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/bin
		./container_status
		echo "Press enter to continue.."
		read
		cd -
		;;
	2)
		cd $ROOTDIR/bin
		./launch_container
		echo "Press enter to continue.."
		read
		cd -
		;;
	3)
		cd $ROOTDIR/bin
		./stop_container
		echo "Press enter to continue.."
		read
		cd -
		;;
	4)
		cd $ROOTDIR/bin
		./attach_container
		echo "Press enter to continue.."
		read
		cd -
		;;
	5)
		cd $ROOTDIR/bin
		./list_nics
		echo "Press enter to continue.."
		read
		cd -
		;;
	w)
		cd $ROOTDIR/bin
		./prune-docker
		echo "Press enter to continue.."
		read
		cd -
		;;
	11)
		cd $ROOTDIR/bin
		time ./create-base-image
		echo "Press enter to continue.."
		read
		cd -
		;;
	13)
		cd $ROOTDIR/bin
		time ./create-cust-image
		echo "Press enter to continue.."
		read
		cd -
		;;
	12)
		cd $ROOTDIR/bin
		time ./stage-image
		echo "Press enter to continue.."
		read
		cd -
		;;
	14)
		cd $ROOTDIR/bin
		./list_image
		echo "Press enter to continue.."
		read
		cd -
		;;
	15)
		cd $ROOTDIR/bin
		./wipe_images
		echo "Press enter to continue.."
		read
		cd -
		;;
	114)
		cd $ROOTDIR/bin
		./list_ec2_instances
		echo "Press enter to continue.."
		read
		cd -
		;;
	115)
		cd $ROOTDIR/bin
		./start_ec2_instance
		echo "Press enter to continue.."
		read
		cd -
		;;
	116)
		cd $ROOTDIR/bin
		./stop_ec2_instance
		echo "Press enter to continue.."
		read
		cd -
		;;
	111)
		cd $ROOTDIR/bin
		./list_vpns
		echo "Press enter to continue.."
		read
		cd -
		;;
	112)
		cd $ROOTDIR/bin
		./create_vpn
		echo "Press enter to continue.."
		read
		cd -
		;;
	113)
		cd $ROOTDIR/bin
		./delete_vpn
		echo "Press enter to continue.."
		read
		cd -
		;;
	i)
		cd $ROOTDIR/bin
		./install_self
		echo "Press enter to continue.."
		read
		cd -
		;;
	a)
		cd $ROOTDIR/bin
		./setup_aws
		echo "Press enter to continue.."
		read
		cd -
		;;
	x) exit ;;
	*) ;;
	esac
done
