#!/bin/bash

TFCLOUD_VERSION="2.0"

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR
[ ! -d /backups ] && mkdir /backups

trap '' 2
while :; do
   LGGRN='\033[1;32m'
   BLUE='\033[1;34m'
   GREY='\033[0;37m'
   CYAN=''
   NC='\033[0m'
   clear
    HOSTNAME=`hostname`
    echo -e "${GREY}$(date +'%x %l:%M %p')${NC}"
    printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
    echo -e "\u2503${BLUE} @ ${NC}`[ -f ../msposapp/.envtype ] && cat ../msposapp/.envtype || echo -e Not Installed`${NC}"
    printf '\u2503'${LGGRN}' )~ Reports'${NC}'\n'
    printf '\u2503''\u2501''\n'
    printf '\u2503'" Free Space:${NC} $(df -h /backups | tail -1 | awk '{print $4}')"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"---\033[0m Backups"'\n'
    printf '\u2503''\033[1m'" 1.\033[0m Summary"'\n'
    printf '\u2503''\033[1m'" 2.\033[0m Detail"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"---\033[0m POSOS"'\n'
    printf '\u2503''\033[1m'" 11.\033[0m Script Tasks"'\n'
    printf '\u2503''\033[1m'" 12.\033[0m PA-DSS Specific Changes"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
    printf '\u2517''\u2501''\n'
	echo -ne "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/bin
		./tfcloudaccountstats.sh 
		tr '|' '\t' < /tmp/TU_STATS_LINUX_Cloud_Backups.txt
                echo -ne "${CYAN}Press enter to continue..${NC}"
                read
                cd -
                ;;
	2)
		cd $ROOTDIR/bin
		./tfcloudaccountdetail.sh
		tr '|' '\t' < /tmp/TU_STATS_LINUX_Cloud_Backup_Detail.txt
                echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	11)
		cd $ROOTDIR/bin
		./posos_tasks.sh 
                echo -ne "${CYAN}Press enter to continue..${NC}"
                read
                cd -
                ;;
	12)
		cd $ROOTDIR/bin
		./posos_padss.sh
                echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	x)	exit
		;;
	*) ;;
	esac
done
