#!/bin/bash

TFCLOUD_VERSION="2.0"

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR
[ ! -d /backups ] && mkdir /backups

trap '' 2
while :; do
    LGGRN='\033[1;32m'
   BLUE='\033[1;34m'
#    BLUE=''
    GREY='\033[0;37m'
#    CYAN='\033[1;36m'
    CYAN=''
    NC='\033[0m'
    clear

HOSTNAME=`hostname`

    echo -e "${GREY}${TFCLOUD_VERSION}  -  ${HOSTNAME}  -  $(date +'%x %l:%M %p')  -  Patched: `date -r /var/log/yum.log`  -  `dmidecode | grep Product | grep -v Not | cut -d: -f2 | sed -e 's/\ //' | head -1`  -  ${NC}"
    printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
#    printf '\u2503'🌷${GREY}' $(hostname)'${NC}'\n'
echo -e "\u2503${BLUE} @ ${NC}`[ -f ../.envtype ] && cat ../.envtype || echo -e Not Installed`${NC}"
    printf '\u2503'${LGGRN}' )~'${NC}'\n'
    printf '\u2523''\u2501''\n'
#echo -e "\u2503 ${HOSTNAME} ${NC}"
#echo -e "\u2503 Type      : `dmidecode | grep Product | grep -v Not | cut -d: -f2 | sed -e 's/\ //' | head -1`${NC}"
printf '\u2503'" Free Space:${NC} $(df -h /backups | tail -1 | awk '{print $4}')"'\n'
##echo -e "\u2503 Patchd: `date -r /var/log/yum.log`${NC}"
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"-- Reports"'\n'
    printf '\u2503''\033[1m'" 1.\033[0m Backups Summary"'\n'
    printf '\u2503''\033[1m'" 2.\033[0m Backups Detail"'\n'
#    printf '\u2503''\033[1m'" 3.\033[0m Repos"'\n'
#    printf '\u2503''\033[1m'" 4.\033[0m Admin"'\n'
#    printf '\u2503''\033[1m'" 5.\033[0m Reports"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
    printf '\u2517''\u2501''\n'
#	echo -ne "${CYAN}Enter selection:${NC} "
	echo -ne "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/bin
		./tfcloudaccountstats.sh 
		cat /tmp/TU_STATS_LINUX_Cloud_Backups.txt
                echo -ne "${CYAN}Press enter to continue..${NC}"
                read
                cd -
                ;;
	2)
		cd $ROOTDIR/bin
		./tfcloudaccountdetail.sh
		cat /tmp/TU_STATS_LINUX_Cloud_Backup_Detail.txt
                echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	x)	exit
		;;
	*) ;;
	esac
done
