#!/usr/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

trap '' 2
while :; do
	clear
	echo "********************************"
	echo "** Linux Admin Tasks           *"
	echo "********************************"
	echo "* [1] Configure Sendgrid Relay *"
	echo "* [2] Convert to CentOS        *"
	echo "*                              *"
	echo "* [d] Documentation            *"
	echo "* [x] Exit                     *"
	echo "********************************"
	echo -n "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/bin
		time ./config_sendgrid
		cd -
		echo "Press enter to continue.."
		read
		;;
	2)
		cd $ROOTDIR/bin
		time ./convert_centos
		cd -
		echo "Press enter to continue.."
		read
		;;
	d)
		./readme.sh
		echo "Press enter to continue.."
		read
		;;
	x) exit ;;
	*) ;;
	esac
done
