#!/bin/bash

trap '' 2
while :
do
clear
echo "*************************************"
echo "***** POS EC2 Instance Service ******"
echo "*************************************"
echo "* [l] List instances                *"
echo "* [c] deploy Customer instance      *"
echo "* [d] Delete instance               *"
echo "* [i] Instance status               *"
echo "* [s] Start/Stop instance           *"
echo "* [g] create customer VPN access    *"
echo "* [v] list customer Vpns            *"
echo "* [a] About                         *"
echo "* [x] eXit                          *"
echo "*************************************"
selection=""
echo -n "Enter selection [l,c,d,i,s,g,v,a,x]: "
read selection
case $selection in
l) ./bin/list_images ; echo "Press enter to continue.." ; read ;;
c) ./bin/build_customer_image ; echo "Press enter to continue.." ; read ;;
d) ./bin/delete_image ; echo "Press enter to continue.." ; read  ;;
i) ./bin/container_status ; echo "Press enter to continue.." ; read  ;;
s) ./bin/start_stop_container ; echo "Press enter to continue.." ; read  ;;
g) ./bin/create_vpn ; echo "Press enter to continue.." ; read  ;;
v) ./bin/list_vpns ; echo "Press enter to continue.." ; read  ;;
a) cat ./doc/about.txt ; echo "Press enter to continue.." ; read ;;
x) cd .. ; exit ;;
*) ;;
esac
done
