#!/usr/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

#figure out why I have to do the next command manually
#scl enable python27 /usr/bin/bash

trap '' 2
while :; do
	clear
echo -en "$(date +%T) - `[ -f .envtype ] && cat .envtype || echo -n Not Installed`\n"
printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
printf '\u2503''\033[1m RTI Cloud Menu\033[0m''\n'
printf '\u2523''\u2501''\n'
printf '\u2503''\033[1m'" 1.\033[0m Running Instances"'\n'
printf '\u2503''\033[1m'" 2.\033[0m Start Instance"'\n'
printf '\u2503''\033[1m'" 3.\033[0m Stop Instance"'\n'
printf '\u2503''\033[1m'" 4.\033[0m Connect to Instance"'\n'
printf '\u2503''\033[1m'" 5.\033[0m List NICs"'\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" 11.\033[0m Build OS Media"'\n'
printf '\u2503''\033[1m'" 12.\033[0m Stage a Server"'\n'
printf '\u2503''\033[1m'" 13.\033[0m List Images"'\n'
printf '\u2503''\033[1m'" 14.\033[0m Delete Image(s)"'\n'
printf '\u2503''\033[1m'" 15."'\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" 111.\033[0m Instance Snapshot"'\n'
printf '\u2503''\033[1m'" 112.\033[0m List VPNs"'\n'
printf '\u2503''\033[1m'" 113.\033[0m Create VPN"'\n'
printf '\u2503''\033[1m'" 114.\033[0m Delete VPN"'\n'
printf '\u2503''\033[1m'" 115."'\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" p.\033[0m Purge All"'\n'
printf '\u2503''\033[1m'" d.\033[0m I/C/U Deps"'\n'
printf '\u2503''\033[1m'" a.\033[0m I/C/U AWS"'\n'
printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
printf '\u2517''\u2501''\n'
	echo -n "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/bin
		./container_status
		echo "Press enter to continue.."
		read
		cd -
		;;
	2)
		cd $ROOTDIR/bin
		./launch_container
		echo "Press enter to continue.."
		read
		cd -
		;;
	3)
		cd $ROOTDIR/bin
		./stop_container
		echo "Press enter to continue.."
		read
		cd -
		;;
	4)
		cd $ROOTDIR/bin
		./container_connect
		echo "Press enter to continue.."
		read
		cd -
		;;
	5)
		cd $ROOTDIR/bin
		./list_nics
		echo "Press enter to continue.."
		read
		cd -
		;;
	p)
		cd $ROOTDIR/bin
		./prune-docker
		echo "Press enter to continue.."
		read
		cd -
		;;
	11)
		cd $ROOTDIR/bin
		time ./create-base-image
		echo "Press enter to continue.."
		read
		cd -
		;;
	12)
		cd $ROOTDIR/bin
		time ./stage-image
		echo "Press enter to continue.."
		read
		cd -
		;;
	13)
		cd $ROOTDIR/bin
		./list_image
		echo "Press enter to continue.."
		read
		cd -
		;;
	14)
		cd $ROOTDIR/bin
		./wipe_images
		echo "Press enter to continue.."
		read
		cd -
		;;
	111)
		cd $ROOTDIR/bin
		time ./snapshot_instance
		echo "Press enter to continue.."
		read
		cd -
		;;
	112)
		cd $ROOTDIR/bin
		time ./list_vpns
		echo "Press enter to continue.."
		read
		cd -
		;;
	113)
		cd $ROOTDIR/bin
		time ./create_vpn
		echo "Press enter to continue.."
		read
		cd -
		;;
	114)
		cd $ROOTDIR/bin
		time ./delete_vpn
		echo "Press enter to continue.."
		read
		cd -
		;;
	d)
		cd $ROOTDIR/bin
		./install
		echo "Press enter to continue.."
		read
		cd -
		;;
	a)
		cd $ROOTDIR/bin
		./setup_aws
		echo "Press enter to continue.."
		read
		cd -
		;;
	x) exit ;;
	*) ;;
	esac
done
