#!/usr/bin/bash

HEIGHT=18
WIDTH=35
CHOICE_HEIGHT=15
BACKTITLE="Cloud Services Menu"
TITLE="POS Application Service"
MENU="Enter selection: "

OPTIONS=(1 "Dev/Build"
         2 "Share-Hosted"
         3 "Self-Hosted")

CHOICE=$(dialog --clear \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--menu "$MENU" \
		$HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty)

case $CHOICE in
	1)
		./msposapp/dev-build/MENU2
		;;
	2)
		./msposapp/share-hosted/MENU2
		;;
	3)
		./msposapp/self-hosted/MENU2
		;;
	*) ;;
esac
exit 0
