#!/usr/bin/bash

# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

ROOTDIR="$(pwd)"
export ROOTDIR

#figure out why I have to do the next command manually
#scl enable python27 /usr/bin/bash

trap '' 2
while :; do
	clear
echo -en "$(date +%T)\n"
printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
printf '\u2503''\033[1m Application Service\033[0m''\n'
printf '\u2523''\u2501''\n'
printf '\u2503''\033[1m'" 1.\033[0m Dev/Build"'\n'
printf '\u2503''\033[1m'" 2.\033[0m Share-Hosted"'\n'
printf '\u2503''\033[1m'" 3.\033[0m Self-Hosted"'\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\n'
printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
printf '\u2517''\u2501''\u2501''\n'
	echo -n "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/dev-build
		./MENU
		cd -
		;;
	2)
		cd $ROOTDIR/share-hosted
		./MENU
		cd -
		;;
	3)
		cd $ROOTDIR/self-hosted
		./MENU
		cd -
		;;
	x) exit ;;
	*) ;;
	esac
done
